// <auto-generated />
using System;
using GiaPhaHub_be.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiaPhaHub_be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312172955_AddGenerationToFM")]
    partial class AddGenerationToFM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Avatar")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime");

                    b.Property<int>("FamilyTreeId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeId");

                    b.ToTable("FamilyMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Người sáng lập gia phả",
                            BirthDate = new DateTime(1940, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeathDate = new DateTime(2015, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyTreeId = 1,
                            Gender = "male",
                            Generation = 1,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nguyễn Văn An"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Vợ ông Nguyễn Văn An",
                            BirthDate = new DateTime(1943, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeathDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FamilyTreeId = 1,
                            Gender = "female",
                            Generation = 1,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Trần Thị Bình"
                        },
                        new
                        {
                            Id = 3,
                            Address = "123 Nguyễn Huệ, Quận 1, TP.HCM",
                            Bio = "Con trai cả",
                            BirthDate = new DateTime(1965, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FamilyTreeId = 1,
                            Gender = "male",
                            Generation = 2,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nguyễn Văn Cường",
                            Phone = "0901234567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Nguyễn Huệ, Quận 1, TP.HCM",
                            Bio = "Vợ anh Nguyễn Văn Cường",
                            BirthDate = new DateTime(1968, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FamilyTreeId = 1,
                            Gender = "female",
                            Generation = 2,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Lê Thị Dung",
                            Phone = "0907654321"
                        },
                        new
                        {
                            Id = 5,
                            Address = "456 Lê Lợi, Quận 3, TP.HCM",
                            Bio = "Con gái thứ hai",
                            BirthDate = new DateTime(1970, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FamilyTreeId = 1,
                            Gender = "female",
                            Generation = 2,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nguyễn Thị Em",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 6,
                            Address = "789 Trần Hưng Đạo, Quận 5, TP.HCM",
                            Bio = "Con trai anh Cường",
                            BirthDate = new DateTime(1990, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FamilyTreeId = 1,
                            Gender = "male",
                            Generation = 3,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nguyễn Văn Phong",
                            Phone = "0923456789"
                        },
                        new
                        {
                            Id = 7,
                            Address = "123 Nguyễn Huệ, Quận 1, TP.HCM",
                            Bio = "Con gái anh Cường",
                            BirthDate = new DateTime(1993, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FamilyTreeId = 1,
                            Gender = "female",
                            Generation = 3,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nguyễn Thị Giang",
                            Phone = "0934567890"
                        });
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.FamilyTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("FamilyTrees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gia phả mẫu dùng để minh họa",
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Gia phả họ Nguyễn"
                        });
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FromMemberId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ToMemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromMemberId");

                    b.HasIndex("RelationshipTypeId");

                    b.HasIndex("ToMemberId");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 3,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 1,
                            ToMemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 3,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 2,
                            ToMemberId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 5,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 1,
                            ToMemberId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 5,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 2,
                            ToMemberId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 1,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 3,
                            ToMemberId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 3,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 3,
                            ToMemberId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 3,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 4,
                            ToMemberId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 6,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 1,
                            ToMemberId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 6,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 2,
                            ToMemberId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 7,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 1,
                            ToMemberId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 7,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 2,
                            ToMemberId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromMemberId = 6,
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RelationshipTypeId = 4,
                            ToMemberId = 7
                        });
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.RelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RelationshipTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cha",
                            Name = "Father"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mẹ",
                            Name = "Mother"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vợ/Chồng",
                            Name = "Spouse"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Anh/Chị/Em",
                            Name = "Sibling"
                        });
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53ab9b57-c1dc-4146-8b95-08de7f8eef11"),
                            CreateDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@gmail.com",
                            FullName = "Quản trị viên",
                            IsDelete = false,
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$hwju4D4c5R3PY0ejkd0C8OVvuxmtsYh1QxVVTHkU9FEo.Oz1pHZHG"
                        });
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiredAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRevoked = true,
                            Token = "seed-refresh-token-placeholder",
                            TokenType = "RefreshToken",
                            UserId = "53ab9b57-c1dc-4146-8b95-08de7f8eef11"
                        });
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("GiaPhaHub_be.Domain.Entities.FamilyTree", "FamilyTree")
                        .WithMany("Members")
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("GiaPhaHub_be.Domain.Entities.FamilyMember", "FromMember")
                        .WithMany("FromRelationships")
                        .HasForeignKey("FromMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiaPhaHub_be.Domain.Entities.RelationshipType", "RelationshipType")
                        .WithMany("Relationships")
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiaPhaHub_be.Domain.Entities.FamilyMember", "ToMember")
                        .WithMany("ToRelationships")
                        .HasForeignKey("ToMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromMember");

                    b.Navigation("RelationshipType");

                    b.Navigation("ToMember");
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.FamilyMember", b =>
                {
                    b.Navigation("FromRelationships");

                    b.Navigation("ToRelationships");
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.FamilyTree", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GiaPhaHub_be.Domain.Entities.RelationshipType", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
